# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 13:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identificacion', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'identificacion no valida', 'invalid')])),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'telefono no valido', 'invalid')], verbose_name='Telefono fijo')),
                ('telefono_celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'telefono no valido', 'invalid')], verbose_name='Celular')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.Usuario')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='administrador/')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Tienda')),
            ],
            options={
                'verbose_name': 'Administrador Tienda',
                'verbose_name_plural': 'Administradores de Tiendas',
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.Usuario')),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleado/')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Tienda')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Documento', verbose_name='Tipo de documento'),
        ),
    ]
