# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_administrador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador Tienda', 'verbose_name_plural': 'Administradores de Tiendas'},
        ),
    ]
