# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='A\xf1o')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('inicio', models.TimeField(null=True)),
                ('fin', models.TimeField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Ciudad')),
            ],
            options={
                'verbose_name': 'Configuracion pago por tienda',
                'verbose_name_plural': 'Configuraciones pago por tienda',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Calendario')),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dia de la semana',
                'verbose_name_plural': 'Dias de la semana',
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado')),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labores',
            },
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dias',
            field=models.ManyToManyField(to='operacion.DiaSemana'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
        ),
    ]
