# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20170503_1421'),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioDefecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
            ],
            options={
                'verbose_name': 'Configuracion pago por tienda',
                'verbose_name_plural': 'Configuraciones pago por tienda',
            },
        ),
    ]
