# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('usuario', '0001_initial'),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado', verbose_name='Domiciliario'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Tienda'),
        ),
        migrations.AddField(
            model_name='labor',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado'),
        ),
        migrations.AddField(
            model_name='dia',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Calendario'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Ciudad'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dias',
            field=models.ManyToManyField(to='operacion.DiaSemana'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
        ),
    ]
