# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_preciodefecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preciodefecto',
            options={'verbose_name': 'Configuracion pago por defecto  tienda', 'verbose_name_plural': 'Configuraciones pago por defecto tienda'},
        ),
    ]
