# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_auto_20170409_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='year',
            field=models.IntegerField(verbose_name='A\xf1o'),
        ),
    ]
