# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_auto_20170508_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoLabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(blank=True, max_length=22, null=True, verbose_name='Hora de inicio')),
                ('fin', models.CharField(blank=True, max_length=22, null=True, verbose_name='Hora de fin')),
                ('precio', models.FloatField(default=0)),
                ('horas', models.FloatField(default=0)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Labor')),
            ],
        ),
    ]
