# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_auto_20170409_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labor',
            name='ini',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
