# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('empresa', '0002_auto_20170503_1421'),
        ('operacion', '0004_pagolabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=800, null=True)),
                ('atendido', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado', verbose_name='Domiciliario')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Tienda')),
            ],
            options={
                'verbose_name': 'Observacion',
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='pagolabor',
            options={'verbose_name': 'Pago Labor', 'verbose_name_plural': 'Pago Labores'},
        ),
    ]
