# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0005_auto_20170826_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Tienda'),
        ),
    ]
