# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_auto_20170409_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='festivos',
        ),
    ]
