# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_auto_20170826_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagolabor',
            old_name='horas',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='pagolabor',
            old_name='inicio',
            new_name='ini',
        ),
    ]
