# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0007_auto_20170927_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagolabor',
            name='fin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='pagolabor',
            name='ini',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hora de inicio'),
        ),
    ]
