# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0009_auto_20170428_2033'),
        ('operacion', '0009_auto_20170428_2222'),
    ]

    operations = [
    ]
