# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_auto_20170429_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='inicio',
        ),
    ]
