# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0014_auto_20170429_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='inicio',
            field=models.TimeField(null=True),
        ),
    ]
