# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20170428_2222'),
        ('operacion', '0015_auto_20170429_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.Ciudad'),
            preserve_default=False,
        ),
    ]
