# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='identificacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
