# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 13:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'licencia no valida', 'invalid')])),
                ('identifier', models.CharField(blank=True, max_length=20, null=True)),
                ('numeroS', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'numero no valida', 'invalid')])),
                ('fecha_expedicionS', models.DateField()),
                ('fecha_expiracionS', models.DateField()),
                ('numeroT', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'numero no valida', 'invalid')])),
                ('fecha_expedicionT', models.DateField()),
                ('fecha_expiracionT', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=6, unique=True)),
                ('t_propiedad', models.CharField(max_length=50, unique=True, verbose_name='Tarjeta de Propiedad')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moto Informacion',
                'verbose_name_plural': 'Informaciones de Motos',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=6, unique=True)),
                ('t_propiedad', models.CharField(max_length=50, unique=True, verbose_name='Tarjeta de Propiedad')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
            },
        ),
        migrations.CreateModel(
            name='Motorizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'licencia no valida', 'invalid')])),
                ('identifier', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Motorizado',
                'verbose_name_plural': 'Motorizados',
            },
        ),
        migrations.CreateModel(
            name='Soat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroS', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'numero no valida', 'invalid')])),
                ('fecha_expedicionS', models.DateField()),
                ('fecha_expiracionS', models.DateField()),
            ],
            options={
                'verbose_name': 'Soat',
                'verbose_name_plural': 'Soats',
            },
        ),
        migrations.CreateModel(
            name='Tecno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroT', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'numero no valida', 'invalid')])),
                ('fecha_expedicionT', models.DateField()),
                ('fecha_expiracionT', models.DateField()),
            ],
            options={
                'verbose_name': 'Tecnomecanica',
                'verbose_name_plural': 'Tecnomecanicas',
            },
        ),
    ]
