# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorizado', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorizado',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado'),
        ),
        migrations.AddField(
            model_name='motorizado',
            name='moto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motorizado.Moto'),
        ),
        migrations.AddField(
            model_name='moto',
            name='soat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motorizado.Soat'),
        ),
        migrations.AddField(
            model_name='moto',
            name='tecno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motorizado.Tecno'),
        ),
        migrations.AddField(
            model_name='infomoto',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado'),
        ),
    ]
