# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorizado', '0004_infomoto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomoto',
            name='soat',
        ),
        migrations.RemoveField(
            model_name='infomoto',
            name='tecno',
        ),
    ]
